### ISSUE TITLE
Не собирается проект

### ISSUE THREAD

**Issue by ShunkevichDV** [ostis-dev/sc-machine#193]
Текст ошибки при сборке

[ 77%] Building C object sc-kpm/scp/CMakeFiles/scp.dir/scp_process_creator.c.o
[ 77%] Building C object sc-kpm/scp/CMakeFiles/scp.dir/scp_keynodes.c.o
Linking CXX shared library ../../../bin/extensions/libscp.so
/usr/bin/ld: scp_lib/libscp_lib.a(scp_sys.c.o): перемещение R_X86_64_32 для «.rodata» не может использоваться при создании общего объекта; перекомпилируйте с -fPIC
scp_lib/libscp_lib.a: error adding symbols: Некорректное значение
collect2: error: ld returned 1 exit status
make[2]: **\* [../bin/extensions/libscp.so] Ошибка 1
make[1]: **\* [sc-kpm/scp/CMakeFiles/scp.dir/all] Ошибка 2
make: **\* [all] Ошибка 2

**Comment by deniskoronchik** [comment]
А что за операционная система? На ubuntu 14.04 64bit и на windows 7 64-bit собирается

**Comment by ShunkevichDV** [comment]
Ubuntu 14.04 64bit
Может не все изменения залил в репозиторий

**Comment by deniskoronchik** [comment]
Все, проверил на виртуальной машине

**Comment by ShunkevichDV** [comment]
Ну вот прямо из консоли кинул логи
У студентов то же самое...
