### ISSUE TITLE
sc-memory target users should include directory of sc-memory target sources

### ISSUE THREAD

**Issue by KovalM** [ostis-dev/sc-machine#365]
sc-memory target users had to do include_directories(${SC_MEMORY_SRC}).

For example, when external user wants to use sc-memory target in his target myTarget, he should to do 2 things:
1. To include directory of sc-memory target sources: `include_directories(${SC_MEMORY_SRC})`
2. To link sc-memory: `target_link_libraries(myTarget sc-memory)`

First point is not obvious, hard to understand and not described anywhere.  User should know path to sc-memory sources. 
In normal way, we need to do only second point.

**Comment by deniskoronchik** [comment]
Fixed in #348
